### ISSUE TITLE
Use packaged version of psutil instead of PyPI's version

### ISSUE THREAD

**Issue by mr-c** [galaxyproject/ansible-galaxy-extras#10]
http://packages.ubuntu.com/search?keywords=python-psutil

I can request a backport of 2.x if that is required.

**Comment by jmchilton** [comment]
This wasn't mentioned in the commit message (https://github.com/galaxyproject/ansible-galaxy-extras/commit/22a22099cdbd4529a85b09845c37fc56b1e2671d) but this previously did use the apt version but doesn't because the [SLURM configure script](https://github.com/galaxyproject/ansible-galaxy-extras/blob/master/templates/configure_slurm.py.j2) requires a newer version than was available in apt at the time. Probably the easiest path forward for this would be to adjust the script to allow use of versions of psutil. I would be happy to accept a pull request to adjust this script.

In general these build processes tend to use apt when available but there are times they install things with ``pip``. The argument for using apt is that you get security fixes usually - but I don't imagine anyone would run ``apt-get upgrade`` inside the containers or virtual machines, I think they would just get newer of the containers with bug fixes. In that sense - arguably ``pip`` is always going to have the newer patches and be more secure for this purpose. Is there another reason to prefer apt or are you intending to use these recipes in a different way than I described here where apt has a clearer advantage from a security perspective?

cc-ing @bgruening just to make sure he sees this thread.

**Comment by bgruening** [comment]
I agree with @jmchilton here. We try wherever we can to use debians archive. But for some packages it is hard. I'm not religious about `dpkg` vs. `pip` and I don't see any advantages of trying to use `dpkg` only. That said if you can get a backport we can probably switch back to `apt-get install` (until the next update we urgently need).

@mr-c, looking forward to discuss this in detail at GCC.

**Comment by mr-c** [comment]
A backport will be messy, alas. Working backwards from http://grodola.blogspot.com/2014/01/psutil-20-porting.html I've made a pull request to switch to syntax compatible with psutil 1.x (and forward compatible with the 2.x series) https://github.com/galaxyproject/ansible-galaxy-extras/pull/11

**Comment by mvdbeek** [comment]
So I guess we can close this one.
