### ISSUE TITLE
Install autofs system package breaks GalaxyKickStart

### ISSUE THREAD

**Issue by drosofff** [galaxyproject/ansible-galaxy-extras#164]
@rhpvorderman @afgane 
To let you know that the PR #160 broke the GalaxyKickStart Travis tests.
Stricto sensus the PR works, except that supervisor autofs is in FATAL states. However, the test fails because we build a docker container starting from [artbio/ansible-galaxy-os](https://hub.docker.com/r/artbio/ansible-galaxy-os/~/dockerfile/): here, the task `[galaxyprojectdotorg.galaxy-extras : Install autofs system package]`fails due to a failure in autofs package installation (see https://travis-ci.org/ARTbio/GalaxyKickStart/builds/261895456#L1443).

I'll try to work at a fix of this. In the meantime, I will pin ansible-galaxy-extras role to commit 03e894feface65f9b4c0df1a41fb70c1fe8db159. What would be cool in addition would be to condition cvmfs_client.yml execution with another variable than galaxy_extras_install_packages. That way, GKS could easily skip the cvmfs stuff that is not currently required.

**Comment by afgane** [comment]
There is a conditional for setting up CVMFS in `defaults`: https://github.com/galaxyproject/ansible-galaxy-extras/blob/master/defaults/main.yml#L25

If you build the container by running the tests locally, can you access it after the process fails? The error log is not very helpful as to what's failing (it just says `"* Starting automount...", "   ...fail!"`).

I guess I'll also have to revisit the `FATAL` state because I thought I had fixed it in the last couple of runs I did...

**Comment by drosofff** [comment]
> There is a conditional for setting up CVMFS in defaults: https://github.com/galaxyproject/ansible-galaxy-extras/blob/master/defaults/main.yml#L25

Sure, I hadn't caught it !

**Comment by bgruening** [comment]
@drosofff upps sorry for that. Is this issue still relevant with @afgane suggestion? Please let me know if you have idea how to improve this in the future. In Galaxy Docker land we are always sticking to a specific commit to make sure this does not break things.

**Comment by afgane** [comment]
@drosofff Let's see if that PR fixes this. 

BTW, which error in Supervisor were you seeing:
- `can't find command '/usr/sbin/automount'` → the PR should address this one
- `/usr/sbin/automount: test mount forbidden or incorrect kernel protocol version, kernel protocol version 5.00 or above required` → this on is fixed by running the container with `--privileged` flag)
- `Exited too quickly (process log may have details)` → a reboot fixes this one, which will inevitably happen for an image

**Comment by bgruening** [comment]
@drosofff please let us know if this fixes your problem.

**Comment by drosofff** [comment]
@bgruening nop, there is still the same error when the container is built for the test:

https://travis-ci.org/ARTbio/GalaxyKickStart/builds/269656175#L1375

Not critical for the moment. It's just an issue in the travis test

**Comment by bgruening** [comment]
:( let me know if you need help!
