### ISSUE TITLE
Should there be an SMTP server ansible role/tasks in this repo?

### ISSUE THREAD

**Issue by zfrenchee** [galaxyproject/ansible-galaxy-extras#94]
Galaxy has hooks in galaxy.ini for an SMTP server to send email relating to resetting passwords for example. I'm not sure how usegalaxy does this, but I for @bgruening's docker image, I'd love if there was the option to have an SMTP server painlessly. I've taken a look at https://github.com/debops/ansible-postfix and I think we may be able to integrate postfix into this repo fairly easily, either as a parallel role or just a bunch of tasks. Would that be appropriate for this repo? @jmchilton @natefoo @martenson

**Comment by martenson** [comment]
I am +1 on this given we use password resets and account activations

**Comment by natefoo** [comment]
The risk here is that simply having a host that originates mail on the Internet is not likely to work in a lot of (most?) scenarios. While technically any host can be set up as an MTA, anti-spam measures such as SPF/DKIM/DMARC, not to mention many networks simply dropping outbound connections to port 25, are likely to (silently) prevent mail from being delivered by the configured MTA.

With that in mind, most people probably fall into two categories:

1. Their site has an existing MTA that messages can be submitted to for relay. This is what the existing Galaxy config options are for.
2. They have no MTA.

Since configuring an MTA properly is complicated, doing it automatically would be pretty difficult without the person running the playbook having a good understanding of how to operate an MTA. Not to mention access to site DNS, etc.

All of that said, we could pretty easily set up a simple MTA, but these issues and the likelihood of message delivery failure should be pretty clearly explained in the role documentation.

**Comment by zfrenchee** [comment]
@natefoo I know nothing about these sorts of things, so if you think it's hard/not worth it, I defer to your good judgement. I've been using my personal gmail lately, and was hoping to move away from that to something built into @bgruening 's image, but if it would be overly complicated then no need.
